channels:
  - bioconda
  - jmcmurray
  - conda-forge
  - defaults
dependencies:
  - contextily
  - dill
  - geopandas==0.10.0
  - json
  - jupyterlab
  - matplotlib
  - psycopg2
  - psutil
  - python-decouple
  - rasterio==1.2.9
  - rasterstats
  - scikit-learn
  - scikit-image