name: onstovebinder
channels:
  - conda-forge
dependencies:
  - dill==0.3.6
  - geopandas==0.12.2
  - matplotlib==3.5.2
  - plotnine==0.10.1
  - psutil==5.9.4
  - psycopg2==2.9.3
  - pyproj==3.3.1
  - python==3.10.9
  - python-decouple==3.7
  - rasterio==1.3.3
  - scikit-image==0.19.3
  - svgpathtools==1.6.0
  - svgpath2mpl==1.0.0
