name: onstovejupyter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=>3.10
  - dill
  - geopandas>=0.11
  - jupyterlab
  - matplotlib==3.5.2
  - plotnine>=0.9.0
  - psutil
  - psycopg2
  - python-decouple
  - rasterio>=1.3.0
  - scikit-image
  - svgpathtools
  - svgpath2mpl
