name: onstovejupyter
channels:
  - conda-forge
  - defaults
dependencies:
  - dill
  - geopandas
  - jupyterlab
  - matplotlib<=3.5.2
  - plotnine
  - psutil
  - psycopg2
  - python=>3.10
  - python-decouple
  - rasterio
  - scikit-image
  - svgpathtools
  - svgpath2mpl
