name: onstovejupyter
channels:
  - bioconda
  - jmcmurray
  - conda-forge
  - defaults
dependencies:
  - contextily==1.2.0
  - dill==0.3.5.1
  - geopandas
  - jupyterlab==3.4.5
  - matplotlib==3.5.3
  - plotnine
  - psutil==5.9.1
  - psycopg2==2.9.3
  - python-decouple==3.6
  - rasterio
  - rasterstats==0.17.0
  - scikit-image==0.19.3
  - scikit-learn
  - svgpathtools==1.5.1
  - svgpath2mpl==1.0.0
