name: onstovejupyter
channels:
  - bioconda
  - jmcmurray
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - contextily
  - dill
  - geopandas
  - jupyterlab
  - matplotlib
  - plotnine
  - psutil
  - psycopg2
  - python-decouple
  - rasterio
  - rasterstats
  - scikit-image
  - scikit-learn
  - svgpathtools
  - svgpath2mpl